version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: clonegram_nginx
    ports:
      - "80:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/project/public:cached
      - ./public/storage:/project/public/storage
    links:
      - clonegram
    networks:
      - frontend
  clonegram:
    build: ./
    container_name: clonegram
    volumes:
      - ./:/project:cached
    working_dir: /project
    networks:
      - frontend
      - backend
    environment:
      APP_ENV: local
      APP_KEY: "base64:05VNDWbv5axaVCzWrtTBLMV1T1Ex8ML4dNzWINrWXHY="
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: clonegramdb
      DB_USERNAME: root
      DB_PASSWORD: password
  mysql:
    platform: linux/x86_64
    image: 'mysql:8.0'
    container_name: clonegram_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: clonegramdb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./:/project:ro
    working_dir: /project
    networks:
      - backend

networks:
  frontend:
  backend:
